name: figma
description: A Figma API wrapper library for interacting with Figma documents, written in pure Dart.
version: 7.0.0
homepage: https://github.com/arnemolland/figma
repository: https://github.com/arnemolland/figma
issue_tracker: https://github.com/arnemolland/figma/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  http2: ^2.0.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  collection: ^1.17.2
  copy_with_extension: ^5.0.2

dev_dependencies:
  test: ^1.24.3
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  lints: ^2.1.0
  markdown: ^7.1.0
  args: ^2.4.1
  yaml: ^3.1.2
