name: figma
description: A Figma API wrapper library for interacting with Figma documents, written in pure Dart.
version: 5.0.3
homepage: https://github.com/arnemolland/figma
repository: https://github.com/arnemolland/figma
issue_tracker: https://github.com/arnemolland/figma/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^0.13.5
  http2: ^2.0.1
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  collection: ^1.17.1
  copy_with_extension: ^5.0.0

dev_dependencies:
  test: ^1.23.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  lints: ^2.0.1
  markdown: ^7.0.0
  args: ^2.4.0
  yaml: ^3.1.1
