name: figma
description: A Figma API wrapper library for interacting with Figma documents, written in pure Dart.
version: 3.0.0
homepage: https://github.com/arnemolland/figma
repository: https://github.com/arnemolland/figma
issue_tracker: https://github.com/arnemolland/figma/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http2: ^2.0.0
  json_annotation: ^4.0.1
  equatable: ^2.0.3
  collection: ^1.15.0
  copy_with_extension: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.8
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  dotenv: ^3.0.0
  copy_with_extension_gen: ^2.0.1
